client_id = "fef767ad801a57a040f5be84ec3bbdd4"
name = "USDrop AI"
embedded = false
application_url = "https://usdrop.ai"

[auth]
redirect_urls = [
  "https://usdrop.ai/api/shopify-stores/oauth/callback"
]

[access_scopes]
scopes = "read_products,write_products,read_orders,read_customers,read_inventory"

[webhooks]
api_version = "2024-10"

[webhooks.privacy_compliance]
customer_deletion_url = "https://usdrop.ai/api/shopify-stores/webhooks/customer-deletion"
customer_data_request_url = "https://usdrop.ai/api/shopify-stores/webhooks/customer-data-request"
shop_deletion_url = "https://usdrop.ai/api/shopify-stores/webhooks/shop-deletion"
