import React, { useState } from 'react';
import { Section, Container, AccordionItem } from './ui';
import { FaqItem } from '../types';

const faqData: FaqItem[] = [
  {
    question: "How does USDrop find winning products?",
    answer: "We analyze millions of data points from social media, AliExpress, and top dropshipping stores in real-time. Our algorithms detect trending products before they become saturated, giving you the first-mover advantage."
  },
  {
    question: "Is the AI content suitable for commercial use?",
    answer: "Yes! All images and copy generated by our AI Studio are 100% royalty-free and cleared for commercial use on your Shopify store, Meta ads, and TikTok campaigns."
  },
  {
    question: "Do you integrate with Shopify?",
    answer: "Seamlessly. With one click, you can import products, images, and descriptions directly to your Shopify store. We also support WooCommerce and other major platforms."
  },
  {
    question: "Can I cancel my subscription anytime?",
    answer: "Yes, there are no long-term contracts. You can cancel your subscription at any time from your dashboard. We also offer a 14-day free trial so you can test the platform risk-free."
  },
  {
    question: "How accurate is the profit calculator?",
    answer: "Our profit calculator pulls real-time shipping and product costs from verified suppliers. While we can't predict your exact ad spend, our margin estimates are highly accurate based on current market data."
  }
];

export const FAQ: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <Section id="faq" className="bg-white">
      <Container>
        <div className="grid grid-cols-1 md:grid-cols-12 gap-12">
          <div className="md:col-span-4">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">Frequently Asked Questions</h2>
            <p className="text-slate-600 mb-8">
              Everything you need to know about USDrop and dropshipping. Can't find the answer you're looking for? Reach out to our 24/7 support team.
            </p>
          </div>
          <div className="md:col-span-8">
            <div className="space-y-2 bg-white rounded-2xl p-6 border border-slate-200 shadow-sm">
              {faqData.map((item, index) => (
                <AccordionItem
                  key={index}
                  title={item.question}
                  isOpen={openIndex === index}
                  onToggle={() => setOpenIndex(openIndex === index ? null : index)}
                >
                  {item.answer}
                </AccordionItem>
              ))}
            </div>
          </div>
        </div>
      </Container>
    </Section>
  );
};