import React from 'react';
import { Container, Section, Button, GeneratedImage } from './ui';
import { Search, Image as ImageIcon, Truck, TrendingUp, Globe, Award, ArrowUpRight } from 'lucide-react';

export const FeaturesBento: React.FC = () => {
  return (
    <Section className="bg-slate-50 border-y border-slate-200">
      <Container>
        <div className="text-center mb-16 max-w-3xl mx-auto space-y-6">
          <h2 className="text-4xl md:text-5xl font-bold text-slate-900">
            Everything You Need to Dominate.
          </h2>
          <p className="text-slate-500 text-lg leading-relaxed">
            Stop stitching together 5 different tools. We give you the complete stack to build a 7-figure dropshipping brand in the USA.
          </p>
        </div>

        {/* Massive Asymmetric Grid */}
        <div className="grid grid-cols-1 md:grid-cols-4 grid-rows-[400px_300px_300px] gap-6">
          
          {/* 1. Product Discovery (Large Hero) */}
          <div className="md:col-span-2 md:row-span-2 bg-white rounded-[2.5rem] p-8 md:p-10 border border-slate-200 shadow-sm relative overflow-hidden group hover:shadow-2xl transition-all duration-500">
             <div className="absolute top-10 right-10 z-10 p-4 bg-white rounded-2xl shadow-lg border border-slate-100 hidden md:block animate-in fade-in zoom-in duration-700">
                <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center text-blue-600 mb-2">
                   <Search className="w-6 h-6" />
                </div>
                <div className="text-2xl font-bold text-slate-900">50M+</div>
                <div className="text-xs text-slate-500 font-bold uppercase">Products Scanned</div>
             </div>
             
             <div className="relative z-10 h-full flex flex-col justify-between">
                <div>
                   <h3 className="text-3xl font-bold text-slate-900 mb-4">#1 Product Discovery Engine</h3>
                   <p className="text-slate-500 text-lg max-w-md">Spy on 8-figure stores. Find hidden winners before they go viral. Validated real-time data from TikTok & Meta.</p>
                </div>
                <Button className="w-fit rounded-full px-8 h-12 font-bold bg-slate-900 text-white hover:bg-slate-800">Start Spying</Button>
             </div>

             <div className="absolute bottom-0 right-0 w-3/4 h-3/4 translate-x-12 translate-y-12">
                <div className="w-full h-full bg-slate-50 rounded-tl-[3rem] overflow-hidden border-t border-l border-slate-100 shadow-2xl relative">
                   <GeneratedImage 
                      prompt="grid of ecommerce products, smartwatches, beauty, gadgets, clean minimal aesthetic, white background"
                      className="w-full h-full object-cover opacity-90 group-hover:scale-105 transition-transform duration-1000" 
                   />
                </div>
             </div>
          </div>

          {/* 2. AI Studio (Tall Vertical) */}
          <div className="md:col-span-1 md:row-span-2 bg-slate-900 rounded-[2.5rem] p-8 border border-slate-800 relative overflow-hidden group">
             <div className="absolute inset-0">
                <GeneratedImage 
                   prompt="futuristic fashion model generated by AI, wearing neon streetwear, cinematic lighting, vertical portrait"
                   className="w-full h-full object-cover opacity-60 group-hover:opacity-80 transition-opacity duration-700"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-slate-900 via-transparent to-transparent" />
             </div>
             <div className="relative z-10 h-full flex flex-col justify-end">
                <div className="w-10 h-10 bg-white/20 backdrop-blur rounded-xl flex items-center justify-center text-white mb-4 border border-white/10">
                   <ImageIcon className="w-5 h-5" />
                </div>
                <h3 className="text-2xl font-bold text-white mb-2">AI Creative Studio</h3>
                <p className="text-slate-300 text-sm mb-6">Generate ads & photos instantly. No models needed.</p>
                <div className="flex items-center text-white text-xs font-bold uppercase tracking-wider gap-2">
                   Try Now <ArrowUpRight className="w-4 h-4" />
                </div>
             </div>
          </div>

          {/* 3. Fast Shipping (Small Card) */}
          <div className="md:col-span-1 md:row-span-1 bg-blue-600 rounded-[2.5rem] p-8 text-white relative overflow-hidden group hover:bg-blue-700 transition-colors cursor-pointer">
             <div className="absolute top-0 right-0 p-8 opacity-10 transform rotate-12 group-hover:rotate-0 transition-transform">
                <Truck className="w-24 h-24" />
             </div>
             <h3 className="text-xl font-bold mb-2 relative z-10">Fast US Shipping</h3>
             <p className="text-blue-100 text-sm mb-6 relative z-10">2-5 day delivery via USPS, UPS & FedEx.</p>
             <div className="flex -space-x-3 relative z-10">
                <div className="w-10 h-10 rounded-full border-2 border-blue-500 bg-white flex items-center justify-center text-blue-600 font-bold text-xs">US</div>
                <div className="w-10 h-10 rounded-full border-2 border-blue-500 bg-blue-100 flex items-center justify-center text-blue-600 font-bold text-xs">CA</div>
             </div>
          </div>

          {/* 4. Profit Calc (Small Card) */}
          <div className="md:col-span-1 md:row-span-1 bg-white rounded-[2.5rem] p-8 border border-slate-200 group hover:border-green-200 transition-colors">
             <div className="flex justify-between items-start mb-6">
                <div className="w-12 h-12 bg-green-50 rounded-2xl flex items-center justify-center text-green-600">
                   <TrendingUp className="w-6 h-6" />
                </div>
                <span className="bg-green-100 text-green-700 text-xs font-bold px-2 py-1 rounded-full">+127% ROI</span>
             </div>
             <h3 className="text-lg font-bold text-slate-900 group-hover:text-green-700 transition-colors">Profit Calculator</h3>
             <p className="text-slate-500 text-xs mt-2">Know your margins before you sell.</p>
          </div>

          {/* 5. Academy (Wide) */}
          <div className="md:col-span-2 md:row-span-1 bg-slate-900 rounded-[2.5rem] p-8 flex items-center justify-between relative overflow-hidden">
             <div className="relative z-10">
                <div className="flex items-center gap-2 mb-2 text-amber-400 font-bold text-xs uppercase tracking-wider">
                   <Award className="w-4 h-4" /> Included Free
                </div>
                <h3 className="text-2xl font-bold text-white mb-2">Dropshipping Academy</h3>
                <p className="text-slate-400 text-sm">Master FB Ads & TikTok scaling with expert courses.</p>
             </div>
             <div className="absolute right-0 top-0 w-1/2 h-full mask-gradient-left">
                <GeneratedImage prompt="3d abstract education icons, book, lightbulb, floating, dark background" className="w-full h-full object-cover opacity-50" />
             </div>
          </div>

          {/* 6. Global (Wide) */}
          <div className="md:col-span-2 md:row-span-1 bg-white border border-slate-200 rounded-[2.5rem] p-8 flex items-center justify-between relative overflow-hidden group hover:border-blue-300 transition-all">
             <div className="relative z-10 max-w-sm">
                <h3 className="text-2xl font-bold text-slate-900 mb-2">Sell Globally</h3>
                <p className="text-slate-500 text-sm mb-4">We handle VAT, customs, and currency automatically.</p>
                <Button variant="outline" size="sm" className="rounded-full text-xs font-bold">Explore Markets</Button>
             </div>
             <div className="w-32 h-32 bg-blue-50 rounded-full flex items-center justify-center group-hover:scale-110 transition-transform duration-500">
                <Globe className="w-16 h-16 text-blue-500" strokeWidth={1.5} />
             </div>
          </div>

        </div>
      </Container>
    </Section>
  );
};