import { type Express } from "express";
import { type Server } from "http";

import { registerAuthRoutes } from "./routes/auth";
import { registerAdminRoutes } from "./routes/admin";
import { registerPublicRoutes } from "./routes/public";
import { registerCROChecklistRoutes } from "./routes/cro-checklist";
import { registerMentorshipLeadRoutes } from "./routes/mentorship-leads";
import { registerLearningProgressRoutes } from "./routes/learning-progress";
import { registerActivityTrackingRoutes } from "./routes/activity-tracking";
import { registerLeadScoringRoutes } from "./routes/lead-scoring";
import { registerPaymentLinkRoutes } from "./routes/payment-links";
import { registerAccessControlRoutes } from "./routes/access-control";
import { registerAdminSessionRoutes } from "./routes/admin-sessions";
import { registerAdminTicketRoutes } from "./routes/admin-tickets";
import { registerAdminClientRoutes } from "./routes/admin-clients";
import { registerAdminLLCRoutes } from "./routes/admin-llc";
import { registerAdminVideoRoutes } from "./routes/admin-videos";
import { registerAdminLinkRoutes } from "./routes/admin-links";
import { registerUserTicketRoutes } from "./routes/user-tickets";
import { registerAdminRoadmapContentRoutes } from "./routes/admin-roadmap-content";
import { registerAdminCROContentRoutes } from "./routes/admin-cro-content";
import { registerShopifyRoutes } from "./routes/shopify";
import { registerStoreClaimRoutes } from "./routes/store-claims";
import { registerShopifyAppRoutes } from "./routes/shopify-app";
import { registerEmailRoutes } from "./routes/email";

export async function registerRoutes(server: Server, app: Express) {
  registerAuthRoutes(app);
  registerAdminRoutes(app);
  registerShopifyRoutes(app);
  registerShopifyAppRoutes(app);
  registerStoreClaimRoutes(app);
  registerPublicRoutes(app);
  registerCROChecklistRoutes(app);
  registerMentorshipLeadRoutes(app);
  registerLearningProgressRoutes(app);
  registerActivityTrackingRoutes(app);
  registerLeadScoringRoutes(app);
  registerPaymentLinkRoutes(app);
  registerAccessControlRoutes(app);
  registerAdminSessionRoutes(app);
  registerAdminTicketRoutes(app);
  registerAdminClientRoutes(app);
  registerAdminLLCRoutes(app);
  registerAdminVideoRoutes(app);
  registerAdminLinkRoutes(app);
  registerUserTicketRoutes(app);
  registerAdminRoadmapContentRoutes(app);
  registerAdminCROContentRoutes(app);
  registerEmailRoutes(app);
}
