import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ConditionalChatbotBubble } from "@/components/chat/conditional-chatbot-bubble";
import { AuthProvider } from "@/contexts/auth-context";
import { UnifiedUserProvider } from "@/contexts/unified-user-context";
import { UserPlanProvider } from "@/contexts/user-plan-context";
import { OnboardingProvider } from "@/contexts/onboarding-context";
import { Toaster } from "@/components/ui/toast";
import { ReactQueryProvider } from "@/contexts/react-query-provider";
import { ErrorBoundary } from "@/components/ui/error-boundary";

import { AuthLoadingGate } from "@/components/auth/auth-loading-gate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "USDrop AI - World's # 1 All-in-One Dropshipping Platform",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
        suppressHydrationWarning
      >
        <ReactQueryProvider>
          <AuthProvider>
            <UnifiedUserProvider>
              <UserPlanProvider>
                <OnboardingProvider>
                  <ErrorBoundary>
                    <AuthLoadingGate>
                      {children}
                    </AuthLoadingGate>
                  </ErrorBoundary>
                  <Toaster />
                </OnboardingProvider>
              </UserPlanProvider>
            </UnifiedUserProvider>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
