
import { MotionFadeIn } from "@/components/motion/MotionFadeIn"
import { DISTANCE, DURATION } from "@/lib/motion"
import { ArrowUpRight, Trophy, Cpu, Ban, Users } from "lucide-react"

const USPs = [
  {
    id: 1,
    label: "All-in-One Platform",
    number: "01",
    bgColor: "bg-[#D4F0E0]",
    icon: Cpu,
  },
  {
    id: 2,
    label: "Fast. Reliable. AI-Powered.",
    number: "02",
    bgColor: "bg-[#E8E0FF]",
    icon: Trophy,
  },
  {
    id: 3,
    label: "No Ads. No Bloat.",
    number: "03",
    bgColor: "bg-[#D4F0E0]",
    icon: Ban,
  },
  {
    id: 4,
    label: "Trusted by 10,000+ Sellers",
    number: "04",
    bgColor: "bg-[#F8E2FE]",
    icon: Users,
  },
]

const Stats = [
  {
    id: 1,
    metric: "$2M+",
    label: "Revenue Generated by Users",
  },
  {
    id: 2,
    metric: "70%",
    label: "Faster Product Research",
  },
  {
    id: 3,
    metric: "65%",
    label: "Higher Conversion Rates",
  },
  {
    id: 4,
    metric: "45%",
    label: "Less Time Wasted",
  },
]

export function ProblemSolution() {
  return (
    <section className="py-16 lg:py-24 relative overflow-hidden">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-[1000px] mx-auto text-center space-y-12">
          {/* Top Badge */}
          <MotionFadeIn direction="up" distance={DISTANCE.md} duration={DURATION.slow}>
            <div className="bg-[#323140] text-white text-[13px] font-medium px-4 py-2 rounded-[8px] w-fit mx-auto">
              How it works
            </div>
          </MotionFadeIn>

          {/* Main Heading */}
          <MotionFadeIn direction="up" distance={DISTANCE.lg} delay={0.1} duration={DURATION.slow}>
            <h2 className="text-4xl sm:text-5xl lg:text-6xl font-medium text-black tracking-[-0.04em] leading-tight">
              Designed Around Your Business
            </h2>
          </MotionFadeIn>

          {/* USP Pills Grid */}
          <MotionFadeIn direction="up" distance={DISTANCE.lg} delay={0.2} duration={DURATION.slow}>
            <div className="grid md:grid-cols-2 gap-4 lg:gap-6">
              {USPs.map((usp, index) => {
                const IconComponent = usp.icon
                return (
                  <div
                    key={usp.id}
                    className={`${usp.bgColor} rounded-[20px] p-6 flex items-center justify-between`}
                    data-testid={`usp-pill-${index + 1}`}
                  >
                    <div className="flex items-center gap-4">
                      <IconComponent className="w-6 h-6 text-gray-700 flex-shrink-0" />
                      <span className="text-lg font-medium text-gray-900 text-left">
                        {usp.label}
                      </span>
                    </div>
                    <div className="flex-shrink-0 bg-white rounded-full w-10 h-10 flex items-center justify-center">
                      <span className="text-sm font-bold text-gray-900">{usp.number}</span>
                    </div>
                  </div>
                )
              })}
            </div>
          </MotionFadeIn>

          {/* Stats Bar */}
          <MotionFadeIn direction="up" distance={DISTANCE.lg} delay={0.3} duration={DURATION.slow}>
            <div className="grid md:grid-cols-4 gap-6 mt-16">
              {Stats.map((stat) => (
                <div key={stat.id} className="flex flex-col items-center gap-3" data-testid={`stat-${stat.id}`}>
                  <div className="w-10 h-10 rounded-full bg-gray-200 flex items-center justify-center">
                    <ArrowUpRight className="w-5 h-5 text-gray-700" />
                  </div>
                  <div className="space-y-1">
                    <p className="text-3xl font-bold text-gray-900">{stat.metric}</p>
                    <p className="text-sm text-gray-600">{stat.label}</p>
                  </div>
                </div>
              ))}
            </div>
          </MotionFadeIn>
        </div>
      </div>
    </section>
  )
}


